#!/bin/bash -eu

# fzf
ln -sf `pwd`/bin/in-new-term-function /usr/local/bin/in-new-term-function
brew update
brew install --HEAD fzf
/usr/local/opt/fzf/install --all

pip install --upgrade pynvim

echo "Open vim and run: PlugInstall"
